# Blacklist
branches:
  except:
    - gh-pages

- os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env:
        global:
    - GH_REPO_NAME: Project_E
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen_log.txt
    - GH_REPO_REF: github.com/AN0DA/Project_E.git
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    
# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
